Feature/gym 40 be create auditor class
Sourcery-Graduates/GymAppBE pull request #11
Opened 2024-10-15 14:27 UTC by Valentine-456

# So, I think I added Audit class for Spring JPA

## How to test:
- go to (http://localhost:8080/swagger-ui/index.html)[http://localhost:8080/swagger-ui/index.html];
- there you will see, the endpoints for permission: get all, create one, and get one by id
- try them in postman

Fields createdBy and ModifiedBy are autofilled with UUID: `00000000-0000-0000-0000-000000000001`

-----------------------
# Important:

I disabled the spring security for now in the main application file. So, no blocking by security for now

2024-10-15 14:33 UTC, przemyslawren commented on src/main/java/com/sourcery/gymapp/backend/authentication/service/PermissionService.java
> +    }
If you are creating the permissions the delete method is missing

2024-10-15 14:34 UTC, przemyslawren commented on src/main/java/com/sourcery/gymapp/backend/authentication/controller/PermissionController.java
> +    }
Also delete endpoint missing

2024-10-15 14:35 UTC, przemyslawren commented on src/main/java/com/sourcery/gymapp/backend/authentication/controller/PermissionController.java
> +import org.springframework.web.bind.annotation.*;
IMPORT WITH * ???

2024-10-15 14:38 UTC, przemyslawren commented on src/main/java/com/sourcery/gymapp/backend/authentication/controller/PermissionController.java
> +    public PermissionController(PermissionService permissionService) {
Maybe let's use @RequiredArgsConstructor instead of manually

2024-10-15 14:40 UTC, przemyslawren requested changes
Delete Permission is missing, let's stick to the single imports, and let's use lombok for consistency

2024-10-16 10:29 UTC, Ka1zerov requested changes
So, we basically need a changelog with a permission to add permissions

example:
--changeset TymofiiSkrypko:insert-roles
INSERT INTO roles (name, created_by, modified_by) VALUES
('Admin', 1, 1),
('Client', 1, 1);

--changeset TymofiiSkrypko:assign-permissions-to-admin
INSERT INTO role_permissions (role_id, permission_id, level, created_by, modified_by) VALUES
((SELECT id FROM roles WHERE name = 'Admin'), (SELECT id FROM permissions WHERE name = 'ADD_MED_SERVICE'), 'ALLOW', 1, 1);

2024-10-16 10:29 UTC, Ka1zerov commented on src/main/java/com/sourcery/gymapp/backend/authentication/controller/PermissionController.java
> +public class PermissionController {
there have to be a permissions to do crud operations with this controller.
Cause we don't want an average user to accidentally do any CRUD with these

2024-10-16 11:45 UTC, przemyslawren approved these changes
LGTM

2024-10-16 11:50 UTC, Ka1zerov approved these changes
great job

2024-10-16 11:50 UTC, merged