Feauture/gym 64 be connect user registration and profile creation by sending an event between 2 modules spring events
Sourcery-Graduates/GymAppBE pull request #48
Opened 2024-12-30 13:40 UTC by Valentine-456

2025-01-23 12:15 UTC, Ka1zerov commented on docker-compose.yaml
> +  kafka1:
do we really need **3** brokers?

2025-01-23 12:34 UTC, Valentine-456 commented on docker-compose.yaml
> +  kafka1:
The internet says: `Scalability: Multiple brokers allow Kafka to handle more data and serve more producers and consumers. Data is spread across brokers by dividing topics into partitions, each of which is managed by a separate broker. Fault Tolerance: If one broker fails, other brokers in the cluster can take over.` 
But the system will work with 1 broker as well. We can decrease this number. I picked 3 because itt was recommended by the course

2025-01-23 14:44 UTC, przemyslawren approved these changes
LGTM

2025-01-23 14:48 UTC, Ka1zerov requested changes
Great Job!
It looks fantastic how you did all of that.

2025-01-23 14:48 UTC, Ka1zerov commented on src/main/java/com/sourcery/gymapp/backend/userProfile/service/ProfileCurrentUserService.java
> +            return AuditorConfig.AuditorAwareImpl.SYSTEM_USER_UUID;
getSystemUserUuid

2025-01-23 14:48 UTC, Ka1zerov commented on src/main/java/com/sourcery/gymapp/backend/globalconfig/KafkaTopicCreationConfig.java
> +                            .replicas(3)
This usually should not be hardcoded, but if you really wanna do that:
```
private static final int DEFAULT_PARTITIONS = 3;
private static final int DEFAULT_REPLICAS = 3;
```

2025-01-23 14:48 UTC, Ka1zerov commented on src/main/java/com/sourcery/gymapp/backend/userProfile/service/UserProfileService.java
> +                .findUserProfileByUserId(event.userId())
would we be able to use "exists" here?

2025-01-23 22:06 UTC, Valentine-456 commented on src/main/java/com/sourcery/gymapp/backend/authentication/service/AuthService.java
> +        kafkaEventsProducer.sendRegistrationEvent(event);
Ok, I see, this concern is valid. However after small research - I found out that transaction may roll out in 2 scenarios:
- JPA fails, but in this case sending an event is after the repository saves the data. If there will be an error, execution simply will not get to event sending, and data will be rolled back (everything is ok).
- Event sending fails. While data is saved to DB in one module, it will never reach the other. But in this case, system will not break (it will just have an empty profile, like we did before). In fact this might introduce another concern - user receives positive response from server that he is registered, but the transaction is rolled back after event failure, so they need to register again?

LMKWYT

2025-01-27 08:50 UTC, Ka1zerov commented on docker-compose.yaml
> +  kafka1:
I read that the optimal way would be to have 1 for development, 3 for prod; but actually we can leave it as it is, cause having several brokers is kinda one of the Kafka`s features

2025-02-05 09:44 UTC, Ka1zerov approved these changes

2025-02-05 09:46 UTC, merged